; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "HLANG Compiler"
#define MyAppVersion "2.2.2"
#define MyAppPublisher "Henry Liu"
#define MyAppURL "N/A"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0B45CAE8-480A-430E-A7A9-FC9CDEF067A5}
AppName=HLANG
AppVersion=2.2.2
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\HLANG
DefaultGroupName=HLANG
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename=HLANG-Setup
SolidCompression=yes
WizardStyle=modern dynamic
ChangesEnvironment=yes
SetupIconFile=icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\Henry Liu\Desktop\HLANG Source\The-HLANG-Compiler-and-Terminal\HLANG 2.1\Windows\*"; \
DestDir: "{app}"; \
Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Tasks]
Name: "addtopath"; Description: "Add HLANG to PATH"; Flags: checkedonce

[Registry]
Root: HKCU; Subkey: "Software\Classes\.hlang"; ValueType: string; ValueName: ""; ValueData: "HLANGFile"; Flags: uninsdeletevalue

Root: HKCU; Subkey: "Software\Classes\HLANGFile"; ValueType: string; ValueName: ""; ValueData: "HLANG Source File"; Flags: uninsdeletekey

Root: HKCU; Subkey: "Software\Classes\HLANGFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\icon.ico"

Root: HKCU; Subkey: "Software\Classes\HLANGFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\hsh.bat"" ""%1"""

[Code]
procedure EnvAddPath(Path: string);
var
  OrigPath: string;
begin
  if RegQueryStringValue(HKEY_CURRENT_USER,
    'Environment', 'Path', OrigPath) then
  begin
    if Pos(';' + Uppercase(Path) + ';',
       ';' + Uppercase(OrigPath) + ';') = 0 then
      RegWriteStringValue(HKEY_CURRENT_USER,
        'Environment',
        'Path',
        OrigPath + ';' + Path);
  end
  else
    RegWriteStringValue(HKEY_CURRENT_USER,
      'Environment',
      'Path',
      Path);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssPostInstall) and WizardIsTaskSelected('addtopath') then
    EnvAddPath(ExpandConstant('{app}'));
end;
